### PR TITLE
Rectangle Frame displayed

### PR DESCRIPTION
**Pull request by Tanish-16**
Some changes and few additions have been done to display a rectangular frame on the face.
With Mask
Without Mask

### CODE REVIEW

**Comment by aarpit1010** [comment]
@Tanish-16 
It works fine..
But could you make it better by showing accuracy too along with the text MASK/NO MASK.
That would solve 2 issues in one PR...
You can take the help from this file for the accuracy code..
`Issue#8_IIT2019044.ipynb`

P.S. : Make the changes in `Issue#5_IIT2019092.ipynb` only...

**Comment by aarpit1010** [comment]
@Tanish-16 
Could you pls add screenshots

**Comment by Tanish-16** [comment]
With Mask and Accuracy
Without Mask and Accuracy

**Comment by aarpit1010** [comment]
@Tanish-16 
The accuracy for MASK is very less and seems to be wrong...
You have used `predict_proba` for measuring accuracy which actually measures only the probability of 1 (not masked in this case)...
So, for measuring probability of 0 you will have to subtract it from 1 and then calculate.
Also in the succeeding if-else is it not better to write the condition based on probability calculated rather than pred..?

**Comment by Tanish-16** [comment]
with mask (2)

**Comment by aarpit1010** [comment]
@Tanish-16 
nice work...

**Review by aarpit1010 — APPROVED** [review]

**Pull request merged**
